// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA554zf20T_MoRWeJUhF44YualDjFHR0z4',
    appId: '1:46425100916:web:dda7b4e39a234ebfb53721',
    messagingSenderId: '46425100916',
    projectId: 'epsib3cda-5a7f1',
    authDomain: 'epsib3cda-5a7f1.firebaseapp.com',
    storageBucket: 'epsib3cda-5a7f1.appspot.com',
    measurementId: 'G-F536FXR6XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUtPTuemMFIMLekGgq5YabBVsAuAaZhk',
    appId: '1:46425100916:android:988a1a803b3d6779b53721',
    messagingSenderId: '46425100916',
    projectId: 'epsib3cda-5a7f1',
    storageBucket: 'epsib3cda-5a7f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWuJG9rBP_RDOga65OZRRY0rQy6n19Qzw',
    appId: '1:46425100916:ios:8b28ba50aa62ca98b53721',
    messagingSenderId: '46425100916',
    projectId: 'epsib3cda-5a7f1',
    storageBucket: 'epsib3cda-5a7f1.appspot.com',
    iosClientId: '46425100916-7gnku8fbgivchvrfhq9shr0mnn7uhfd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectepsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWuJG9rBP_RDOga65OZRRY0rQy6n19Qzw',
    appId: '1:46425100916:ios:8b28ba50aa62ca98b53721',
    messagingSenderId: '46425100916',
    projectId: 'epsib3cda-5a7f1',
    storageBucket: 'epsib3cda-5a7f1.appspot.com',
    iosClientId: '46425100916-7gnku8fbgivchvrfhq9shr0mnn7uhfd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectepsi',
  );
}
